networks:
  novanet:

volumes:
  pgdata:
  zkdata:
  kafkadata:

services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_USER: novapos
      POSTGRES_PASSWORD: novapos
      POSTGRES_DB: novapos
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: "no"
    networks: [novanet]

  redis:
    image: redis:7
    ports:
      - "6379:6379"
    networks: [novanet]

  zookeeper:
    image: bitnami/zookeeper:3.8
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    ports:
      - "2181:2181"
    volumes:
      - zkdata:/bitnami/zookeeper
    networks: [novanet]

  kafka:
    image: bitnami/kafka:3.7
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092
      - KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE=true
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
    ports:
      - "9092:9092"
    depends_on:
      - zookeeper
    volumes:
      - kafkadata:/bitnami/kafka
    healthcheck:
      test: ["CMD-SHELL", "kafka-topics.sh --bootstrap-server localhost:9092 --list >/dev/null 2>&1"]
      interval: 10s
      timeout: 5s
      retries: 6
      start_period: 20s
    networks: [novanet]

  product-service:
    build:
      context: .
      dockerfile: services/product-service/Dockerfile
    environment:
      - DATABASE_URL=postgres://novapos:novapos@postgres:5432/novapos
      - KAFKA_BOOTSTRAP=kafka:9092
      - RUST_LOG=info
      - JWT_ISSUER=https://auth.novapos.local
      - JWT_AUDIENCE=novapos-frontend,novapos-admin,novapos-postgres
      - JWT_JWKS_URL=http://auth-service:8085/.well-known/jwks.json
    depends_on:
      postgres:
        condition: service_started
      kafka:
        condition: service_healthy
    ports: ["8081:8081"]
    networks: [novanet]

  auth-service:
    build:
      context: .
      dockerfile: services/auth-service/Dockerfile
    environment:
      - DATABASE_URL=postgres://novapos:novapos@postgres:5432/novapos
      - RUST_LOG=info
      - JWT_ISSUER=https://auth.novapos.local
      - JWT_AUDIENCE=novapos-frontend,novapos-admin,novapos-postgres
      - JWT_DEV_PRIVATE_KEY_PEM_FILE=/run/secrets/jwt_dev_private_key
    secrets:
      - jwt_dev_private_key
    depends_on: [postgres]
    ports: ["8085:8085"]
    networks: [novanet]
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8085/.well-known/jwks.json"]
      interval: 10s
      timeout: 5s
      retries: 5

  order-service:
    build:
      context: .
      dockerfile: services/order-service/Dockerfile
    environment:
      - DATABASE_URL=postgres://novapos:novapos@postgres:5432/novapos
      - KAFKA_BOOTSTRAP=kafka:9092
      - INTEGRATION_URL=http://integration-gateway:8083
      - RUST_LOG=info
      - JWT_ISSUER=https://auth.novapos.local
      - JWT_AUDIENCE=novapos-frontend,novapos-admin,novapos-postgres
      - JWT_JWKS_URL=http://auth-service:8085/.well-known/jwks.json
    depends_on:
      postgres:
        condition: service_started
      kafka:
        condition: service_healthy
      integration-gateway:
        condition: service_started
    ports: ["8084:8084"]
    networks: [novanet]

  inventory-service:
    build:
      context: .
      dockerfile: services/inventory-service/Dockerfile
    environment:
      - DATABASE_URL=postgres://novapos:novapos@postgres:5432/novapos
      - KAFKA_BOOTSTRAP=kafka:9092
      - RUST_LOG=info
      - JWT_ISSUER=https://auth.novapos.local
      - JWT_AUDIENCE=novapos-frontend,novapos-admin,novapos-postgres
      - JWT_JWKS_URL=http://auth-service:8085/.well-known/jwks.json
    depends_on:
      postgres:
        condition: service_started
      kafka:
        condition: service_healthy
    ports: ["8087:8087"]
    networks: [novanet]

  analytics-service:
    build:
      context: .
      dockerfile: services/analytics-service/Dockerfile
    environment:
      - DATABASE_URL=postgres://novapos:novapos@postgres:5432/novapos
      - KAFKA_BOOTSTRAP=kafka:9092
      - RUST_LOG=info
      - JWT_ISSUER=https://auth.novapos.local
      - JWT_AUDIENCE=novapos-frontend,novapos-admin,novapos-postgres
      - JWT_JWKS_URL=http://auth-service:8085/.well-known/jwks.json
    depends_on:
      postgres:
        condition: service_started
      kafka:
        condition: service_healthy
    ports: ["8082:8082"]
    networks: [novanet]

  loyalty-service:
    build:
      context: .
      dockerfile: services/loyalty-service/Dockerfile
    environment:
      - DATABASE_URL=postgres://novapos:novapos@postgres:5432/novapos
      - KAFKA_BOOTSTRAP=kafka:9092
      - RUST_LOG=info
      - JWT_ISSUER=https://auth.novapos.local
      - JWT_AUDIENCE=novapos-frontend,novapos-admin,novapos-postgres
      - JWT_JWKS_URL=http://auth-service:8085/.well-known/jwks.json
    depends_on:
      postgres:
        condition: service_started
      kafka:
        condition: service_healthy
    ports: ["8088:8088"]
    networks: [novanet]

  customer-service:
    build:
      context: .
      dockerfile: services/customer-service/Dockerfile
    environment:
      - CUSTOMER_MASTER_KEY=oDzFP29jTB7sNhBJCaVRJQvTIhhPCi+WuSSmdPxGNIs=
      - DATABASE_URL=postgres://novapos:novapos@postgres:5432/novapos
      - RUST_LOG=info
      - JWT_ISSUER=https://auth.novapos.local
      - JWT_AUDIENCE=novapos-frontend,novapos-admin,novapos-postgres
      - JWT_JWKS_URL=http://auth-service:8085/.well-known/jwks.json
    depends_on:
      auth-service:
        condition: service_healthy
      postgres:
        condition: service_started
    ports: ["8089:8089"]
    networks: [novanet]

  payment-service:
    build:
      context: .
      dockerfile: services/payment-service/Dockerfile
    environment:
      - KAFKA_BOOTSTRAP=kafka:9092
      - RUST_LOG=info
      - JWT_ISSUER=https://auth.novapos.local
      - JWT_AUDIENCE=novapos-frontend,novapos-admin,novapos-postgres
      - JWT_JWKS_URL=http://auth-service:8085/.well-known/jwks.json
    depends_on:
      kafka:
        condition: service_healthy
    ports: ["8086:8086"]
    networks: [novanet]

  integration-gateway:
    build:
      context: .
      dockerfile: services/integration-gateway/Dockerfile
    environment:
      - DATABASE_URL=postgres://novapos:novapos@postgres:5432/novapos
      - KAFKA_BOOTSTRAP=kafka:9092
      - PAYMENT_SERVICE_URL=http://payment-service:8086
      - ORDER_SERVICE_URL=http://order-service:8084
      # Optional: adjust refresh cadence for API key cache (defaults to 60s)
      - KEY_REFRESH_SECONDS=60
      # Uncomment and set if testing Coinbase integration:
      # - COINBASE_COMMERCE_API_KEY=
      # - COINBASE_WEBHOOK_SECRET=
      - RUST_LOG=info
      - JWT_ISSUER=https://auth.novapos.local
      - JWT_AUDIENCE=novapos-frontend,novapos-admin,novapos-postgres
      - JWT_JWKS_URL=http://auth-service:8085/.well-known/jwks.json
    depends_on:
      kafka:
        condition: service_healthy
      payment-service:
        condition: service_started
    ports: ["8083:8083"]
    networks: [novanet]

  # Frontends (optional in dev)
  pos-app:
    build:
      context: .
      dockerfile: frontends/pos-app/Dockerfile
    depends_on: [product-service]
    ports: ["3000:80"]
    networks: [novanet]

  admin-portal:
    build:
      context: .
      dockerfile: frontends/admin-portal/Dockerfile
    depends_on: [auth-service]
    ports: ["3001:80"]
    networks: [novanet]

  kafka-topics-init:
    image: bitnami/kafka:3.7
    depends_on:
      kafka:
        condition: service_healthy
    entrypoint: /bin/bash
    command:
      - -c
      - |
          set -e
          echo 'Waiting for Kafka to be reachable...'
          until kafka-topics.sh --bootstrap-server kafka:9092 --list >/dev/null 2>&1; do
            sleep 2
          done
          for topic in payment.completed payment.failed order.completed; do
            kafka-topics.sh --create --if-not-exists --topic "$$topic" --bootstrap-server kafka:9092 --replication-factor 1 --partitions 1
          done
    restart: "no"
    networks: [novanet]



secrets:
  jwt_dev_private_key:
    file: ./jwt-dev.pem

