ALTER TABLE orders ADD COLUMN customer_id UUID NULL;
ALTER TABLE orders ADD COLUMN offline BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE orders ADD COLUMN created_at TIMESTAMPTZ NOT NULL DEFAULT NOW();
