name: Backend CI

on:
  push:
    paths:
      - "services/**"
      - ".github/workflows/backend.yml"
  pull_request:
    paths:
      - "services/**"
      - ".github/workflows/backend.yml"
  workflow_dispatch:

jobs:
  rust:
    runs-on: ubuntu-latest
    env:
      SQLX_OFFLINE: "true"   # build SQLx macros without DB connection
    steps:
      - uses: actions/checkout@v4

      - name: Set up Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Cache Cargo registry + build
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('services/**/Cargo.toml') }}-${{ hashFiles('services/Cargo.lock') }}

      - name: Build (workspace)
        run: cargo build --workspace --locked

      - name: Test (workspace)
        run: cargo test --workspace --locked
