name: ci
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - run: cargo test --workspace
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: cd frontends/pos-app && npm ci && npm run build
      - run: cd frontends/admin-portal && npm ci && npm run build
