name: Frontend CI

on:
  push:
    paths:
      - "frontends/**"
      - ".github/workflows/frontend.yml"
  pull_request:
    paths:
      - "frontends/**"
      - ".github/workflows/frontend.yml"
  workflow_dispatch:

jobs:
  pos_app:
    runs-on: ubuntu-latest
    env:
      CI: true
    defaults:
      run:
        working-directory: frontends/pos-app
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "npm"
          cache-dependency-path: frontends/pos-app/package-lock.json

      - name: Install deps
        run: npm ci

      - name: Lint
        run: npm run lint --if-present

      - name: Typecheck
        run: npx tsc --noEmit

      - name: Test
        run: npm test --if-present -- --watch=false

      - name: Build
        run: npm run build

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps

      - name: Cache Playwright Browsers
        uses: actions/cache@v4
        with:
          path: ~/.cache/ms-playwright
          key: ${{ runner.os }}-playwright-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-playwright-

      - name: E2E (Playwright)
        run: npm run test:e2e -- --reporter=dot --workers=1 --trace=on-first-retry

      - name: Upload Playwright Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: pos-app-playwright-report
          path: frontends/pos-app/playwright-report

  admin_portal:
    runs-on: ubuntu-latest
    env:
      CI: true
    defaults:
      run:
        working-directory: frontends/admin-portal
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "npm"
          cache-dependency-path: frontends/admin-portal/package-lock.json

      - name: Install deps
        run: npm ci

      - name: Lint
        run: npm run lint --if-present

      - name: Typecheck
        run: npx tsc --noEmit

      - name: Test
        run: npm test --if-present -- --watch=false

      - name: Build
        run: npm run build

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps

      - name: Cache Playwright Browsers
        uses: actions/cache@v4
        with:
          path: ~/.cache/ms-playwright
          key: ${{ runner.os }}-playwright-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-playwright-

      - name: E2E (Playwright)
        run: npm run test:e2e -- --reporter=dot --workers=1 --trace=on-first-retry

      - name: Upload Playwright Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: admin-portal-playwright-report
          path: frontends/admin-portal/playwright-report
